parameters:
  companies:
    - ISalud
    - ExternalCompany

services:
  # Autowire all services in the app except Commands
  App\:
    resource: '../src/*'
    exclude: '../src/Reporting/Command'
    autowire: true
    public: false

  # Autowire all Commands in the app, and make them public to allow for registering in the application
  App\Reporting\Command\:
    resource: '../src/Reporting/Command'
    autowire: true
    public: true
    tags: [console.command]

  App\Reporting\Infrastructure\:
    resource: '../src/Reporting/Infrastructure'
    autowire: true
    public: true
    tags: [console.command]

  App\Reporting\Infrastructure\Service\Source\CompanyListService:
    arguments: ['%companies%']

  App\Reporting\Infrastructure\Service\Source\SourceFactoryInterface: '@App\Reporting\Infrastructure\Service\Source\SourceFactory'

  App\Reporting\Command\ListCompaniesCloseToRenewMonthAheadService:
    arguments: ['@App\Reporting\Infrastructure\Service\Source\SourceFactoryInterface']

  App\Reporting\Infrastructure\Service\Converter:
    arguments: ['../logsfile']

